//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactus.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cactus_Vistavka
    {
        public int ID { get; set; }
        public Nullable<int> ID_Cactus { get; set; }
        public Nullable<int> ID_Vistavka { get; set; }
    
        public virtual Cactus Cactus { get; set; }
        public virtual Vistavka Vistavka { get; set; }
    }
}
